
service: shopify-serverless-auth

provider:
  name: aws
  runtime: nodejs10.x

  environment:
    POST_AUTH_REDIRECT: ''
    SHOPIFY_API_KEY: ${env:SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${env:SHOPIFY_API_SECRET}

functions:
  authinit:
    handler: auth.init
    events:
      - http:
          path: auth/init
          method: get
  authtoken:
    handler: auth.token
    events:
      - http:
          path: auth/token
          method: get
  authpage:
    handler: auth.page
    events:
      - http:
          path: test
          method: get
